### ISSUE TITLE
(node:19736) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open '-----BEGIN CERTIFICATE-----

### ISSUE THREAD

**Issue by Harrrrry** [Mastercard/client-encryption-nodejs#20] opened 2021-03-17 07:12 UTC
Hello,

I am using my private and cert.pem file in config, File is available in folder but still the code give me below error.

`encryptionCertificate: fs.readFileSync(
    path.resolve(__dirname, "../public/images/demo/m8.demo.cert.pem")
  ),
  privateKey: fs.readFileSync(
    path.resolve(__dirname, "../public/images/demo/m8.demo.key.no_pasword.key")
  ),`

`(node:19736) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open '-----BEGIN CERTIFICATE-----
MIERE.....ERERER
-----END CERTIFICATE-----
'
    at Object.openSync (fs.js:439:3)
    at Object.readFileSync (fs.js:344:35)
    at readPublicCertificate (D:\node project\MiaWallet\node_modules\mastercard-client-encryption\lib\mcapi\crypto\crypto.js:189:33)
    at new Crypto (D:\node project\MiaWallet\node_modules\mastercard-client-encryption\lib\mcapi\crypto\crypto.js:18:32)
    at new FieldLevelEncryption (D:\node project\MiaWallet\node_modules\mastercard-client-encryption\lib\mcapi\fle\field-level-encryption.js:15:17)
    at addCard (D:\node project\MiaWallet\controller\index.js:209:17)
    at Layer.handle [as handle_request] (D:\node project\MiaWallet\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\node project\MiaWallet\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (D:\node project\MiaWallet\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (D:\node project\MiaWallet\node_modules\express\lib\router\layer.js:95:5)
(node:19736) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:19736) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:19736) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open '-----BEGIN CERTIFICATE--`

**Comment by Harrrrry** [comment] 2021-03-17 07:27
Hello,

I Change the below code
`  encryptionCertificate: path.resolve(
    __dirname,
    "../public/images/demo/m8.demo.cert.pem"
  ),
  privateKey: path.resolve(
    __dirname,
    "../public/images/demo/m8.demo.key.no_pasword.key"
  ),`
  
  Now i am getting the below error
  `(node:12272) UnhandledPromiseRejectionWarning: Error: Too few bytes to read ASN.1 value.
    at _fromDer (D:\node project\MiaWallet\node_modules\node-forge\lib\asn1.js:487:19)
    at _fromDer (D:\node project\MiaWallet\node_modules\node-forge\lib\asn1.js:524:20)
    at Object.asn1.fromDer (D:\node project\MiaWallet\node_modules\node-forge\lib\asn1.js:448:10)
    at loadPrivateKey (D:\node project\MiaWallet\node_modules\mastercard-client-encryption\lib\mcapi\crypto\crypto.js:182:50)
    at new Crypto (D:\node project\MiaWallet\node_modules\mastercard-client-encryption\lib\mcapi\crypto\crypto.js:22:23)
    at new FieldLevelEncryption (D:\node project\MiaWallet\node_modules\mastercard-client-encryption\lib\mcapi\fle\field-level-encryption.js:15:17)
    at addCard (D:\node project\MiaWallet\controller\index.js:181:17)
    at Layer.handle [as handle_request] (D:\node project\MiaWallet\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\node project\MiaWallet\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (D:\node project\MiaWallet\node_modules\express\lib\router\route.js:112:3)
(node:12272) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:12272) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

**Comment by jaaufauvre** [comment] 2021-03-17 08:40
Hi @Harrrrry, please make sure:
* The API your are trying to consume is a Mastercard API with [end-to-end payload encryption](https://developer.mastercard.com/platform/documentation/security-and-authentication/securing-sensitive-data-using-payload-encryption/)
* `m8.demo.key.no_pasword.key` is a valid decryption key
* `m8.demo.cert.pem` is a valid encryption certificate

Here is a reference tutorial for what you are trying to achieve: [Generating and Configuring a Mastercard API Client](https://developer.mastercard.com/platform/documentation/security-and-authentication/generating-and-configuring-a-mastercard-api-client/). 
It explains how to generate and configure a simple API client for consuming APIs offered on the [Mastercard Developer portal](https://developer.mastercard.com/apis). You will find inside how to enable payload encryption.

**Comment by Harrrrry** [comment] 2021-03-17 09:07
@jaaufauvre,

Yes below are the valid keys
m8.demo.key.no_pasword.key
m8.demo.cert.pem

Can you explain me this error **UnhandledPromiseRejectionWarning: Error: Too few bytes to read ASN.1 value. at _fromDer**

**Comment by jaaufauvre** [comment] 2021-03-17 09:15
No I can't with the level of information you provide. 

Please share a project so that we can reproduce the error.

**Comment by Harrrrry** [comment] 2021-03-17 09:25
Here is my code for the controller

`"use strict";

const {
  Buffer,
  createECDH,
  createCipheriv,
  createDecipheriv,
} = require("@ravshansbox/browser-crypto");
const forge = require("node-forge");
const fs = require("fs");
var path = require("path");
const axios = require("axios");
const https = require("https");
const utf8 = require("utf8");
//const crypto = require('crypto');
var aes256 = require("aes256");
var base64 = require("base-64");
const crypto = require("crypto");
const CIPHER_ALGORITHM = "aes-256-ctr";
const clientEncryption = require("mastercard-client-encryption");

const config = {
  paths: [
    {
      path: "/merchant/harendra/user/rohit/card",
      toEncrypt: [
        {
          element: "cardInfo.encryptedData",
          obj: "cardInfo",
        },
        {
          element: "encryptedPayload.encryptedData",
          obj: "encryptedPayload",
        },
      ],
      toDecrypt: [
        {
          element: "tokenDetail",
          obj: "tokenDetail.encryptedData",
        },
      ],
    },
  ],
  ivFieldName: "iv",
  encryptedKeyFieldName: "encryptedKey",
  encryptedValueFieldName: "encryptedData",
  dataEncoding: "hex",
  encryptionCertificate: path.resolve(
    __dirname,
    "../public/images/demo/m8.demo.cert.pem"
  ),
  privateKey: path.resolve(
    __dirname,
    "../public/images/demo/m8.demo.key.no_pasword.key"
  ),
  oaepPaddingDigestAlgorithm: "SHA-256",
};

const CommonController = {
  genrateKey: (req, res) => {
    //console.log("I am in generateKey api");
    const p12Content = fs.readFileSync(
      path.resolve(__dirname, "../public/images/demo/m9.demo.pfx"), // this is the m9 private
      "binary"
    );
    const p12Asn1 = forge.asn1.fromDer(p12Content, false);

    const p12 = forge.pkcs12.pkcs12FromAsn1(p12Asn1, false, "demo");
    const keyBags = p12.getBags({
      bagType: forge.pki.oids.pkcs8ShroudedKeyBag,
    });
    var bag = keyBags[forge.pki.oids.pkcs8ShroudedKeyBag][0];
    var privateKey = bag.key;
    const signingKey = forge.pki.privateKeyToPem(privateKey);
    //console.log("generateKey is working fine");
    // console.log("Key", signingKey);
    return signingKey;
  },

  genrateToken: async (http_type, apipath, apimethod, req = {}) => {
    // console.log("I am in generateToken api");
    const signingKey = await CommonController.genrateKey();

    const consumerKey =
      "5A0BE4532776010A1F84CA5200BE0D52E4DB642D8B1AE510F0E5179287ED8A67"; // this should be the m10 key
    const uri = apipath + apimethod; // THIS
    console.log(uri);
    const method = http_type;
    if (http_type == "GET") {
      var data = "";
    } else {
      var data = JSON.stringify(req);
    }

    const oauth = require("mastercard-oauth1-signer");
    //console.log("payload", payload);
    const authHeader = oauth.getAuthorizationHeader(
      uri,
      method,
      data,
      consumerKey,
      signingKey
    );
    console.log("Token", authHeader);
    // res.send(authHeader);
    return authHeader;
  },

  getUserList: async (req, res) => {
    console.log("I am in userlist api");
    var request = require("request");
    var http_type = "GET";
    var apimethod = "user/count";
    req = {};
    var apipath = "https://mmtb2b.test.meawallet.com/mmt/tokenization/v1/";
    var token = await CommonController.genrateToken(
      http_type,
      apipath,
      apimethod,
      req
    );
    //res.send(token);
    request(
      {
        method: http_type,
        url: apipath + apimethod,
        headers: {
          "Content-Type": "application/json",
          "Mea-Trace-Id": "a40c9f66-32ef-4b61-a8d4-b4902e6d00db",
          Authorization: token,
        },
        secureProtocol: "TLSv1_2_method",
        key: fs.readFileSync(
          path.resolve(
            __dirname,
            "../public/images/demo/m8.demo.key.no_pasword.key"
          )
        ), // m8 private key
        cert: fs.readFileSync(
          path.resolve(__dirname, "../public/images/demo/m8.demo.cert.pem")
        ), //
      },
      function (error, response, body) {
        console.log("Error:", error);
        console.log("body:", body);
        //console.log("response:", response);
        res.send(body);
      }
    );
  },
  addCard: async (req, res) => {
    console.log("I am in addcard api");
    var request = require("request");
    var http_type = "POST";
    var apimethod = "merchant/harendra/user/rohit/card";

    // var carddata = {
    //   card_id: "1234567890123456",
    //   pan: "54235223223232323",
    //   expiry_year: 23,
    //   expiry_month: 12,
    //   cardholder_name: "JOHN DOE",
    //   status: "ACTIVE",
    // };

    var fundingAccountInfo = {
      encryptedPayload: {
        encryptedData: {
          cardAccountData: {
            card_id: "1234567890123456",
            pan: "54235223223232323",
            expiry_year: 23,
            expiry_month: 12,
            cardholder_name: "JOHN DOE",
            status: "ACTIVE",
          },
        },
      },
    };

    const fle = new clientEncryption.FieldLevelEncryption(config);
    // ...
    let responsePayload = fle.encrypt(
      "/merchant/harendra/user/rohit/card",
      header,
      fundingAccountInfo
    );
    res.send(responsePayload);
    // const secret =
    //   "3082020A0282020100C7227FEB5820386F6DF250D3B44C84FAFBE053B4FB08F588224A7835D5F258B9E526731CFD813671B29014C31A7A19A2B950AABE359CBFBFC88B384449133ADA0C12B7AA7B30F9439824A2BF10BF2E0E1921E5528B22CE1A888CC26B439BAEAAE0A4ED07A923CE73F5E20126784B17814FB3081D54A06072AAC7393FD40E37CF3064E571645EFA57680AF7DA6A1A9F3D9B3A05B3BE6C24CCA315384FCCE9D21064097F137EC14B50AACAF11351D74D89056DEABE5ACA2A2D5E949585545E9A47239F604A524FA0AA4CC169D4055CB9FD7A461223625B513F6C51EFE09EE71EE587B7F5B0FFF610871ADBEF98A403665994FF02A34443B6373DD52089FA48D97BBAB11B3F8627C1616BA657A63F20936B8CC6E18038EBDFC3D6D8E166EED27C975769352F4E0AEA2AEA1F8B291023F361C6076803D95CA8E44A9F63C5093FCE11998BE5EFAC1D3D3B37B63D93EF0DFEE42EE8FE9CD242A3AB150B81E53C5D4F457088F6C2BD95FB42E7942C8167972478D1C5E78F89382E0DC271DBF797B4D269F0E372424458FB757C76C99988DE5DA6BB9BE300E09673DB249A8974165C4026D2D076C75B18CD2D527E9079515FFA4C49025C96B4CC5BCE1642F262E39A9CACD02D0D8C8C69CFC263471146DB2BA0CCE50654B1ED6A26492512AA3543349C9C149B41049167990EFCD7F7CC612630E07B4554C4F0F27E8B6DD97F6A42A1EE490203010001";
    // req = {
    //   public_key_fingerprint:
    //     "AFD598D67A54C20B6DFEFD0FD499C2515B065BEF260E8FF548609E7A7EC5A749",
    //   encrypted_key: secret,
    //   encrypted_data: data,
    //   iv: iv_string,
    // };

    // var apipath = "https://mmtb2b.test.meawallet.com/mmt/tokenization/v1/";

    // var token = await CommonController.genrateToken(
    //   http_type,
    //   apipath,
    //   apimethod,
    //   req
    // );

    // request(
    //   {
    //     method: http_type,
    //     url: apipath + apimethod,
    //     headers: {
    //       "Content-Type": "application/json",
    //       "Mea-Trace-Id": "a40c9f66-32ef-4b61-a8d4-b4902e6d00db",
    //       Authorization: token,
    //     },
    //     body: JSON.stringify(req),
    //     secureProtocol: "TLSv1_2_method",
    //     key: fs.readFileSync(
    //       path.resolve(
    //         __dirname,
    //         "../public/images/demo/m8.demo.key.no_pasword.key"
    //       )
    //     ), // m8 private key
    //     cert: fs.readFileSync(
    //       path.resolve(__dirname, "../public/images/demo/m8.demo.cert.pem")
    //     ), //
    //   },
    //   function (error, response, body) {
    //     console.log("Error:", error);
    //     // console.log("body:", response);
    //     console.log("response:", response.statusCode);
    //     res.send(body);
    //   }
    // );
  },
};

module.exports = CommonController;
`

**Comment by jaaufauvre** [comment] 2021-03-17 10:58
Hi @Harrrrry,

This is not the first time your ask for help in a "_it doesn't work, please help_" mode.

When asking for support or reporting a potential defect, please provide a reproducible test case. If someone else can reproduce your problem, they often have a good chance of fixing the problem. 

* Keep the surface area small. Remove everything but the error, so that we don't have to dig in the code you dumped in this thread
* Provide the relevant files (like the certificate and key files in this case). If they are secrets, then provide test files causing the same behaviour
* If you can't format the code properly (like above), then provide a ZIP file and the command(s) to run

After you provided this reproducible test case we will run it and (a) provide a solution to your issue _if_ the problem is on your side, (b) fix the defect _if_ the problem is in this library.

If you are unable to provide this test case, we will unfortunately close the issue.

Thanks for your understanding!

**Comment by Harrrrry** [comment] 2021-03-17 13:35
@jaaufauvre 
should I provide the complete code or part of code which produce the error?

Also i can't share the keys here but I am very much sure it is from the CONFIG object
`encryptionCertificate: path.resolve(
__dirname,
"../public/images/demo/m8.demo.cert.pem"
),
privateKey: path.resolve(
__dirname,
"../public/images/demo/m8.demo.key.no_pasword.key"
),`

**Comment by jaaufauvre** [comment] 2021-03-24 10:34
Hi @Harrrrry, did you get a chance to work on the reproducible test case requested above?

To answer your question "_Keep the surface area small. Remove everything but the error, so that we don't have to dig in the code you dumped in this thread_"

Thanks!

**Comment by jaaufauvre** [comment] 2021-04-29 06:05
Hi @Harrrrry, I'm closing this one. Do not hesitate to reopen it with the requested information in case you still face the issue. Thanks!

**Closed by jaaufauvre** 2021-04-29 06:05 UTC
